<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soccer" nsURI="http://org.metable.hex.soccer.domain.emf/soccer/v1.0"
    nsPrefix="org.metable.hex.soccer.domain.emf">
  <eClassifiers xsi:type="ecore:EEnum" name="EmfFieldPosition">
    <eLiterals name="FORWARD"/>
    <eLiterals name="MIDDLE" value="1"/>
    <eLiterals name="BACK" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EmfSpecialityPosition">
    <eLiterals name="STRIKER"/>
    <eLiterals name="WING" value="1"/>
    <eLiterals name="LEFT" value="2"/>
    <eLiterals name="RIGHT" value="3"/>
    <eLiterals name="CENTER" value="4"/>
    <eLiterals name="ATTACKING" value="5"/>
    <eLiterals name="DEFENSIVE" value="6"/>
    <eLiterals name="SWEEPER" value="7"/>
    <eLiterals name="KEEPER" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldPosition" eType="#//EmfFieldPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialityPosition" eType="#//EmfSpecialityPosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfPlayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfRosterMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//EmfPlayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//EmfPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfTeam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roster" upperBound="-1"
        eType="#//EmfRosterMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfSoccerUniverse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//EmfPlayer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="-1"
        eType="#//EmfTeam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positions" upperBound="-1"
        eType="#//EmfPosition" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
